version: "3.7"

services:
  db:
    image: postgres
    volumes:
        - ./ddl/postgres.init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./query:/query
    environment:
        - POSTGRES_USER=team9
        - POSTGRES_PASSWORD=dbteam9
        - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  adminer:
    image: adminer
    ports:
        - 28080:8080
